# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

collections:
  people:
    output: true
  projects:
    output: true
  policy:
    output: true
  minijobs:
    output: true
  seminars:
    permalink: /seminars/:year/:month/:day/:title:output_ext
    output: true
  ad-hoc-seminars:
    permalink: /adhoc/:year/:month/:day/:title:output_ext
    output: true
logo: logo.png
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlatcl/jekyll-theme
style: mlatcl
description: This is a page of ML researchers based in the Computer Laboratory working in collaboration with Carl Henrik Ek, Ferenc Huszar, Neil Lawrence and Jessica Montgomery.
baseurl: ''
markdown: kramdown
twitter_username: mlatcl
github_username: mlatcl
display:
  copy_button:
    bibtex: true
    endnote: true
    ris: true
    apa: true
  comments: false
ghub:
  edit: true
  repository: internal
future: true
publisher: The Computer Laboratory
author:
  name: ML@CL
  github: mlatcl

analytics:
  google: 
    tracking_id: UA-184894912-1
future: true
